# nixpacks.toml

[build]
# Specify the base image
image = "php:8.1-fpm"

# Define your build commands
commands = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan migrate --force",
]

[web]
# Set the web server configuration
port = "8080"
command = "php artisan serve --host=0.0.0.0 --port=8080"
