# nixpacks.toml

[phases]
install = "composer install --optimize-autoloader --no-dev"
migrate = "php artisan migrate --force"
cache = "php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
command = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
