[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev > composer_install.log 2>&1 || { echo 'Composer install failed'; exit 1; }",
  "cat composer_install.log",  # Display logs
  "ls -la /app/vendor || { echo 'Vendor directory not found'; exit 1; }",
  "php artisan key:generate --no-interaction || { echo 'Key generation failed'; exit 1; }"
]

[phases.migrate]
cmds = [
  "if [ -d /app/vendor ]; then php artisan migrate --force; else echo 'Vendor directory not found, skipping migrations'; fi"
]

[phases.cache]
cmds = [
  "sleep 2",
  "if [ -d /app/vendor ]; then php artisan optimize; else echo 'Vendor directory not found, skipping cache commands'; fi"
]

[deploy]
command = "nginx -g 'daemon off;'"  # Start Nginx to serve the application
