# nixpacks.toml

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev",  # Install dependencies first
  "ls -la /app/vendor",  # Check if vendor directory is created
  "php artisan key:generate"  # Generate application key if not already done
]

[phases.migrate]
cmds = [
  "php artisan migrate --force"  # Run migrations
]

[phases.cache]
cmds = [
  "sleep 2",  # Delay to ensure everything is ready
  "if [ -d /app/vendor ]; then \
      php artisan config:clear && \
      php artisan route:clear && \
      php artisan view:clear && \
      php artisan config:cache && \
      php artisan route:cache && \
      php artisan view:cache; \
    else \
      echo 'Vendor directory not found, skipping cache commands'; \
    fi"
]

[deploy]
command = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"  # Start the application
