# nixpacks.toml

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev || { echo 'Composer install failed'; exit 1; }",  # Install dependencies first
  "ls -la /app/vendor || { echo 'Vendor directory not found'; exit 1; }",  # Check if vendor directory is created
  "php artisan key:generate || { echo 'Key generation failed'; exit 1; }"  # Generate application key if not already done
]

[phases.migrate]
cmds = [
  "if [ -d /app/vendor ]; then php artisan migrate --force; else echo 'Vendor directory not found, skipping migrations'; exit 1; fi"  # Run migrations if vendor exists
]

[phases.cache]
cmds = [
  "sleep 2",  # Delay to ensure everything is ready
  "if [ -d /app/vendor ]; then php artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache; else echo 'Vendor directory not found, skipping cache commands'; fi"
]

[deploy]
command = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"  # Start the application
