# nixpacks.toml

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev" # Install dependencies first
]

[phases.migrate]
cmds = [
  "php artisan migrate --force"  # Run migrations
]

[phases.cache]
cmds = [
  "php artisan config:clear",     # Clear the config cache
  "php artisan route:clear",      # Clear the route cache
  "php artisan view:clear",       # Clear the view cache
  "php artisan config:cache",     # Cache the config
  "php artisan route:cache",      # Cache the routes
  "php artisan view:cache"        # Cache the views
]

[deploy]
command = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}" # Start the application
